DROP VIEW IF EXISTS user_total_savings CASCADE;
DROP VIEW IF EXISTS goal_balances CASCADE;
DROP VIEW IF EXISTS monthly_activity CASCADE;

DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS goals CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
